#!/bin/bash
source ./parameter

SU_process=false
## following parameters only valid when SU_process is true 
# system endian 
system_endian='little_endian'
## taper
max_percentage=0.08
## filter frequency
filt_freq=2,4,15,20
amps=0,1,1,0
## gain
scale=1
