#!/bin/bash

# paper GJI,2016, Experiement I, figure 1-3

### job info
Job_title='Exp1'
system='slurm'  # slurm, lsf or pbs
queue='tiger'   # serial,tiger(princeton) ...
max_nproc_per_node=16 # max number of processors per node
ntasks=1
NPROC_SPECFEM=4
WallTime=10
compiler='ifort'
GPU_MODE=false
job='kernel' # modeling,kernel,inversion
solver='specfem2D' # specfem2D, specfem3D
ReStart=true   # true--Relaunch all files; false--Start from current status

### paths
package_path="$seisDD/seisDD"
specfem_path="$seisDD/specfem2d"

### observations 
ExistDATA=true
# if exist provide path, otherwise ignore
DATA_DIR="$seisDD/GJI2016/Exp1/data"

### model paths
target_velocity_dir=" "
initial_velocity_dir="$seisDD/GJI2016/Exp1/model_init_bin"

### forward modeling
# number of samples in data
NSTEP=4800
# sample rate
deltat=0.06 #s  
f0=0.084
# number of receivers
NREC=2
# number of sources
NSRC=1
# measurement (x,y,z,p)
data_list='y'

### kernel construction
# measurement type (CC WD ET ED IP MT MA) 
measurement_list=CC
# misfit_type (AD, DD, AD+DD)
misfit_type_list=DD
# similarity threshold for DD 
cc_threshold=0.90

## inversion parameters
kernel_list='beta_kernel'
precond=false
precond_name='Hessian2_kernel'
z_precond=0.0
model_list='vs'

# optimization(SD CG QN)
opt_scheme=QN

# iteration limit
iter_start=1
iter_end=1

### preprocessing
Wscale=0
wavelet_path="$seisDD/seisDD/lib/WT_basis"

TIME_WINDOW=true
VEL_TOP=3900
VEL_BOT=2200

### postprocessing
# smooth
smooth=true
sigma_x=15000
sigma_z=15000
sigma_x_rate=0.0
sigma_z_rate=0.0

## Display details
DISPLAY_DETAILS=true
