#!/bin/bash

# paper GJI,2016, Experiement IV, figure 13

### job info
Job_title='Exp4'
system='slurm'  # slurm, lsf or pbs
queue='tiger'   # serial,tiger(princeton) ...
max_nproc_per_node=16 # max number of processors per node
ntasks=32
NPROC_SPECFEM=1
WallTime=60
compiler='ifort'
GPU_MODE=false
job='kernel' # modeling,kernel,inversion
solver='specfem2D' # specfem2D, specfem3D
ReStart=true   # true--Relaunch all files; false--Start from current status

### paths
package_path="$seisDD/seisDD"
specfem_path="$seisDD/specfem2d"

### observations 
ExistDATA=false
# if exist provide path, otherwise ignore
DATA_DIR="$seisDD/GJI2016/Exp4/data"

### model paths
target_velocity_dir="$seisDD/GJI2016/Exp4/model_true_bin "
initial_velocity_dir="$seisDD/GJI2016/Exp4/model_init_bin"

### forward modeling
# number of samples in data
NSTEP=4800
# sample rate
deltat=0.000026 #s  
f0=260
# number of receivers
NREC=293
# number of sources
NSRC=32
# measurement (x,y,z,p)
data_list='y'

### kernel construction
# measurement type (CC WD ET ED IP MT MA) 
measurement_list=CC
# misfit_type (AD, DD, AD+DD)
misfit_type_list=DD
# similarity threshold for DD 
cc_threshold=0.90
# geometry threshold 
DD_min=1
DD_max=50

## inversion parameters
kernel_list='beta_kernel'
precond=false
precond_list='hessian2_kernel'
z_precond=0.0
model_list='vs'

# optimization(SD CG QN)
opt_scheme=QN

# iteration limit
iter_start=1
iter_end=1

### preprocessing
Wscale=0
wavelet_path="$seisDD/seisDD/lib/WT_basis"

is_window=1
Vmin=4000
Vmax=5000

### postprocessing
# smooth
smooth=false
sigma_x=3
sigma_z=3
sigma_x_rate=0.0
sigma_z_rate=0.0

## Display details
DISPLAY_DETAILS=false
